apiVersion: batch/v1
kind: Job
metadata:
  name: "playwithsql-status-bench-$DB"
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: playwithsql
    spec:
      containers:
      - image: vincentserpoul/playwithsql-cmd-status
        imagePullPolicy: Always
        name: playwithsql-status-bench
        args:
          - "-db=$DB"
          - "-host=$HOST"
          - "-loops=$LOOPS"
          - "-maxconns=$MAXCONNS"
        resources:
          requests:
            memory: "3Gi"
            cpu: "0.5"
          limits:
            memory: "3.5Gi"
            cpu: "1" 
      restartPolicy: Never
  # affinity:
  #   podAntiAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchExpressions:
  #         - key: type
  #           operator: In
  #           values:
  #           - db